
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://ken-dev.info"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: '/personal-site'

# Google tracking id

google-tracking-id: "UA-120242789-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Kenneth Nwafor"
title: "Kenneth Nwafor"
description: "Website and blog of Kenneth Nwafor"
keywords: "Tech, Data Science, Machine Learning, Blockchain, Python, Django"
#favicon: "../img/favicon.ico"

################
# Header layout #
################

#black-favicon: "../img/black-lab-glass.ico"

background-img: "../img/network-machine-learning-ss-1920.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 1
start-delay: 10
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The best way to get a project done faster is to start sooner."
  - text: "Every good work of software starts by scratching a developer's personal itch."
  - text: "Data is the sword of the twenty-first century, those who wield it well, the samurai."
  - text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand."
  - text: "Documentation is the castor oil of programming. Managers think it is good for programmers and programmers hate it!."
  - text: "How does a project get to be a year late?... One day at a time."
  - test: "It's OK to figure out murder mysteries, but you shouldn't need to figure out code. You should be able to read it."
  - text: "Plan to throw one (implementation) away; you will, anyhow."
  - text: "Before software can be reusable it first has to be usable."
  - text: "If you don't strive to be in control, you will be under it, sooner or later."
  - text: "I found my true love in the manifolds of a deep neural network, but she was gone by the next epoch."

me-img: "/img/me.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "ken-dev"
comments-enabled: True

syntax-highlight: True

############
# Timeline #
############

events:

  - image: "/img/timeline/nus.jpg"
    date: "January 2020"
    description: "Completed an 18 months Master degree program in Artificial Intelligence in the National University of Singapore.
    where I also doubled as a Research Assistant for Physics Nobel Laureate <a href='https://en.wikipedia.org/wiki/Konstantin_Novoselov' target='_blank'>Sir Konstantin Novoselov</a>."
    link:
        url: http://www.nus.edu.sg/
        external: True


  - image: "/img/timeline/mkdev_mentor.jpg"
    date: "January 2019"
    description: "Became a programming mentor at <a href='https://mkdev.me/en' target='_blank'>MkDev.me</a>, a programming mentorship platform."


  - image: "/img/timeline/floship.jpeg"
    date: "April 2018"
    description: "Started working as a Python Backend Developer in <a href='https://www.floship.com' target='_blank'>Floship</a>, a Hong Kong based E-commerce and logistics company."


  - image: "/img/timeline/cloud_innopolis.jpg"
    date: "October 2017"
    description: "Started working as a Software Engineer in the <a href='https://university.innopolis.ru/research/iis/cloud_lab/' target='_blank'> Cloud Systems Lab </a> of Innopolis University"

  - image: "/img/timeline/wfys.jpg"
    date: "October 2017"
    description: "Attended <a href='http://futureteam.world' target='_blank'> World Festival of Youth and Students </a> in Sochi, Russia."
    link:
        url: events/2018/06/01/wfys2017.html
        external: False

  - image: "/img/timeline/grad.jpg"
    date: "August 2017"
    description: "Graduated from Innopolis University"

  - image: "/img/timeline/web-resp.png"
    date: "July 2017"
    description: "Started working on WeOut project"

#  - image: "/img/timeline/web-development.png"
#    date: "July 2017"
#    description: " Started working on CashBackFriends project"

#  - image: "/img/timeline/inno-uni.jpg"
#    date: "June - July 2017"
#    description: "Attended Corporate Android Applications Development course in Innopolis"

  - image: "/img/timeline/forum-tatarstan.jpg"
    date: "April 2017"
    description: "Presented project and won second place in Forum Tatarstan"

  - image: "/img/timeline/ranepa.png"
    date: "July 2016"
    description: "Participated in prestigious <a href='http://www.campus4youth.com/' target='_blank'>RANEPA Summer Campus</a>"
    link:
      url: http://www.campus4youth.com/
      external: True

  - image: "/img/timeline/intern.jpg"
    date: "June - September 2016"
    description: "Developer intern at <a href='https://taxnet.ru' target='_blank'>Taxnet</a>"

  - image: "/img/timeline/Robotics.jpg"
    date: "February 2016"
    description: "Participated and won <a href='http://kpfu.ru/itis/primi-uchastie-v-hakatone-39intellektualnye-186972.html' target='_blank'>KFU ITIS Robotics Hackathon</a>"


# First image of the Timeline

timeline-img: "/img/me.jpg"

###########
# Contact #
###########

email: "info@ken-dev.info"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Kenneth Nwafor is a data scientist and software developer with great experience in the tech industry. He loves to write about tech, science and life in general."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/ken4scholars"
  - title: "twitter"
    url: "https://twitter.com/ken4scholars"
  - title: "github"
    url: "https://github.com/ken4scholars"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/ken4scholars"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

destination: docs

# Other SEO settings

logo: "/img/comp-science.jpg"

google_site_verification: "tCbXsmoOkPLWM3caJZcEN86pA9YAC8YViUTKqKg3ciM"